### ISSUE TITLE
鸿蒙闪退

### ISSUE THREAD

**Issue by lininyang** [universeindream/MaiCaiAssistant#16]
悬浮窗问题

**Comment by itwangxiang** [comment]
闪退的话，请下载 v2.1.2 版本，点击 ERROR DETAILS 截图反馈下

**Comment by chenxz2016** [comment]
![微信图片_20220412061827](https://user-images.githubusercontent.com/22885424/162842676-31c4f088-4cf2-495a-b9ff-a49612b9aa4b.jpg)
@itwangxiang 
鸿蒙的系统版本2.0.0.230(C00E230R1P6)

**Comment by itwangxiang** [comment]
v2.1.4 已修复

**Comment by lininyang** [comment]
停在提交失败运力不足的页面。



---- 回复的原邮件 ----
| 发件人 | Kim ***@***.***> |
| 日期 | 2022年04月12日 10:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [universeindream/MaiCaiAssistant] 鸿蒙闪退 (Issue #16) |

v2.1.4 已修复
