### ISSUE TITLE
叮咚买菜因没有可选时间无法持续抢购

### ISSUE THREAD

**Issue by saberxt** [universeindream/MaiCaiAssistant#24]
下午想刷刷看有没有新的运力出来时，买菜助手会因为无法选择送达时间而直接停止点击并响铃，从而无法持续尝试抢购。

**Comment by jwzhang01** [comment]
解决了吗兄弟，我也遇到这个问题了

**Comment by itwangxiang** [comment]
试试 v2.8.0 - 叮咚 app 抢购 - xxx（可重复尝试）

**Comment by saberxt** [comment]
尝试了一下，过了几次之后，就停住了

**Comment by jwzhang01** [comment]
我自己琢磨了个办法，使用2.7.1版本的软件，自己更改程序执行流程：

**Comment by itwangxiang** [comment]
你在选择送达时间步骤设置下，运行后延迟 500 ms 试试，记得反馈下结果哈

**Comment by itwangxiang** [comment]
> 尝试了一下，过了几次之后，就停住了

你在选择送达时间步骤设置下，运行后延迟 500 ms 试试，记得反馈下结果哈

**Comment by jwzhang01** [comment]
2.8.0版本确实会运行几次之后自动停止，我自己琢磨了个办法，使用2.7.1版本的程序，修改程序的执行流程：
选择方案：叮咚-支付宝-自动送达时间  
自己修改默认执行时间，25分钟太短了
前5个步骤不变，到点击重新加载
第6步：立即支付-可重复（程序自带的步骤，不需要修改）
第7步（自定义步骤）：操作类型为"click random node"，节点类型为 txt ;
                                      条件列表：
                                                     1 node exist（key= 选择送达时间）
                                                     2 node not click (key= 选择送达时间）
                                                     3 node no exist（key= 已约满）
第8步（自定义步骤）：操作类型为"back" ,节点类型为 txt ;
                                      条件列表：1 node exist（key= 已约满）
第9步（自定义步骤）：开启 "响铃"和"人工" 两个开关
                                      操作类型为"none"，节点类型为 package_name ; package_name=com,yaya.zone
                                      条件列表：1 app is background  节点类型为 package_name ; package_name=com,yaya.zone

**Comment by itwangxiang** [comment]
> 2.8.0版本确实会运行几次之后自动停止，我自己琢磨了个办法，使用2.7.1版本的程序，修改程序的执行流程：
> 
> 选择方案：叮咚-支付宝-自动送达时间  
> 
> 自己修改默认执行时间，25分钟太短了
> 
> 前5个步骤不变，到点击重新加载
> 
> 第6步：立即支付-可重复（程序自带的步骤，不需要修改）
> 
> 第7步（自定义步骤）：操作类型为"click random node"，节点类型为 txt ;
> 
>                                       条件列表：
> 
>                                                      1 node exist（key= 选择送达时间）
> 
>                                                      2 node not click (key= 选择送达时间）
> 
>                                                      3 node no exist（key= 已约满）
> 
> 第8步（自定义步骤）：操作类型为"back" ,节点类型为 txt ;
> 
>                                       条件列表：1 node exist（key= 已约满）
> 
> 第9步（自定义步骤）：开启 "响铃"和"人工" 两个开关
> 
>                                       操作类型为"none"，节点类型为 package_name ; package_name=com,yaya.zone
> 
>                                       条件列表：1 app is background  节点类型为 package_name ; package_name=com,yaya.zone
> 
> 

可以的，终于有玩家自行修改方案了，点赞👍，理论上 2.8.0 也可以的，方便使用 2.8.0 设置下然后分享下 json 吗，替小白用户感谢你

**Comment by saberxt** [comment]
> 

在我修改deley再该回0之后又正常了，暂时好像没啥问题

**Comment by saberxt** [comment]
> > 尝试了一下，过了几次之后，就停住了
> 
> 你在选择送达时间步骤设置下，运行后延迟 500 ms 试试，记得反馈下结果哈

我之前尝试延迟了一下然后也不太行，但是改回0之后就又感觉正常了，暂时不清楚为什么

**Comment by saberxt** [comment]
![Screenshot_20220418_170228_com univerindream maicaiassistant](https://user-images.githubusercontent.com/103311994/163785253-6073739a-bcc8-4574-8499-326006384010.jpg)

**Comment by jwzhang01** [comment]
- 用2.8.0版本试过了，还是会运行几次之后自动停止，暂时不清楚啥原因，所以又换回了2.7.1版本；

- 我好想用这个来自动执行别的APP，这个也太好用了，已start，博主可以简单出个教程吗:joy:，大概看那些文件之类的，我还没有学过android开发相关的技术，有个简单教程的话就太好了
（比如，com.yaya.zone代表叮咚买菜，这个是在哪里指定呀，修改这个之后，是不是就能换app了:joy:）

**Comment by itwangxiang** [comment]
> * 用2.8.0版本试过了，还是会运行几次之后自动停止，暂时不清楚啥原因，所以又换回了2.7.1版本；
> * 我好想用这个来自动执行别的APP，这个也太好用了，已start，博主可以简单出个教程吗😂，大概看那些文件之类的，我还没有学过android开发相关的技术，有个简单教程的话就太好了
>   （比如，com.yaya.zone代表叮咚买菜，这个是在哪里指定呀，修改这个之后，是不是就能换app了😂）

有空的吧，类似 com.yaya.zone ，会优化成用户选择打开哪一个

**Comment by itwangxiang** [comment]
已处理
