### ISSUE TITLE
小米收集没有悬浮窗

### ISSUE THREAD

**Issue by Yu-Haibo** [universeindream/MaiCaiAssistant#25]
小米开启无障碍后，还是没有悬浮窗出现

**Comment by ShemLau** [comment]
我有悬浮窗 但是点了悬浮窗上面的抢购按钮 就会来回弹 不会激活相应的主程序

**Comment by itwangxiang** [comment]
> 小米开启无障碍后，还是没有悬浮窗出现

杀掉 app，重新启动看看呢

**Comment by itwangxiang** [comment]
> 我有悬浮窗 但是点了悬浮窗上面的抢购按钮 就会来回弹 不会激活相应的主程序

这个 bug 已经修复了

**Comment by itwangxiang** [comment]
#20
