### ISSUE TITLE
三星S22 安卓12 出现错误

### ISSUE THREAD

**Issue by cloud0402** [universeindream/MaiCaiAssistant#26]
![11e0896747ea595f6015db68ca60569](https://user-images.githubusercontent.com/20157750/163066496-df9dafe9-bbbb-4bfd-8acb-1f7254475147.jpg)
三星S22 安卓12

**Comment by itwangxiang** [comment]
你这问题真的，无奈，你下载新的版本试试，不行加微信群

**Comment by cloud0402** [comment]
新版本可以正常打开了，谢谢
