### ISSUE TITLE
请教：美团买菜麻烦增加支持【极速支付】

### ISSUE THREAD

**Issue by jackdiy** [universeindream/MaiCaiAssistant#27]
早起发现报错，停在了抢支付的界面。个人认为可能是方案暂时没有进行下一步的策略，因为我看方案写的是调支付宝或微信支付

当然美团这点很逗，从未听说订单提交待支付是个半本地缓存状态，也就是说我们要抢到支付按钮出来之后继续抢支付队列）

另外，有关盒马团购的抢菜，盒马社区团购其实可以搞个脚本8点刷出列表后一边疯狂勾选SKU一边疯狂点结算，因为抢到之后可以用信用卡付，每个订单的单品还可以随时申请退款。所以先抢先付就完了。（但可能由于要输入支付密码可能不太好完全无人值守）

**Comment by itwangxiang** [comment]
你可以尝试将支付订单页面截图我看看，我尝试新增一个方案，然后你试一下

**Comment by itwangxiang** [comment]
#18

**Comment by jackdiy** [comment]
> 你可以尝试将支付订单页面截图我看看，我尝试新增一个方案，然后你试一下

这两天没进入支付订单页面，我进去了截图给你。
我先给个盒马的出来，美团订单成功之后就是这个样的右下角有个红色的支付按钮。也要一直点。。
![微信图片_20220414111145](https://user-images.githubusercontent.com/23490822/163306363-cfbc5317-561f-4549-95ee-86bfc473a797.jpg)

**Comment by jackdiy** [comment]
> 你可以尝试将支付订单页面截图我看看，我尝试新增一个方案，然后你试一下

可以看这个视频的第41秒，正常其他平台这时候点支付就完了，它从42秒开始，你还要一直点红色的“立即支付”，然后告诉你前面拥堵。（这真的是扯淡，这样做不浪费他们结算服务器并发么，TMD居然提交订单不锁定的，支付还要抢，F*ck）
而盒马就没有这种问题，盒马只要提交了订单，你可以手动慢点付款。

https://www.bilibili.com/video/BV1AY4y1H7Qg?share_source=copy_web
我截图出来了
![微信截图_20220414112306](https://user-images.githubusercontent.com/23490822/163308195-9c9d307b-74a5-4519-8a47-b5a5ad13584c.jpg)

**Comment by xuanxm** [comment]
美团我碰到同样的问题

**Comment by itwangxiang** [comment]
> > 你可以尝试将支付订单页面截图我看看，我尝试新增一个方案，然后你试一下
> 
> 可以看这个视频的第41秒，正常其他平台这时候点支付就完了，它从42秒开始，你还要一直点红色的“立即支付”，然后告诉你前面拥堵。（这真的是扯淡，这样做不浪费他们结算服务器并发么，TMD居然提交订单不锁定的，支付还要抢，F*ck） 而盒马就没有这种问题，盒马只要提交了订单，你可以手动慢点付款。
> 
> https://www.bilibili.com/video/BV1AY4y1H7Qg?share_source=copy_web 我截图出来了 ![微信截图_20220414112306](https://user-images.githubusercontent.com/23490822/163308195-9c9d307b-74a5-4519-8a47-b5a5ad13584c.jpg)
> 
> 这个是盒马的 ![微信图片_20220414111145](https://user-images.githubusercontent.com/23490822/163306363-cfbc5317-561f-4549-95ee-86bfc473a797.jpg)

理论上我会自动执行的呀，可能间隔太短了，导致模拟点击无法触发了，可以设置大一点

**Comment by jackdiy** [comment]
> > > 你可以尝试将支付订单页面截图我看看，我尝试新增一个方案，然后你试一下
> > 
> > 
> > 可以看这个视频的第41秒，正常其他平台这时候点支付就完了，它从42秒开始，你还要一直点红色的“立即支付”，然后告诉你前面拥堵。（这真的是扯淡，这样做不浪费他们结算服务器并发么，TMD居然提交订单不锁定的，支付还要抢，F*ck） 而盒马就没有这种问题，盒马只要提交了订单，你可以手动慢点付款。
> > https://www.bilibili.com/video/BV1AY4y1H7Qg?share_source=copy_web 
> 
> 理论上我会自动执行的呀，可能间隔太短了，导致模拟点击无法触发了，可以设置大一点

看到您辛苦的更新它，我作一定实际情况反馈，它是这样：
先说结果：这这两天美团我都抢到了，您的助手可以抢到订单，只是没有自动支付，后半部分我手动执行极速支付的过程成功了，只是没抢到绿叶菜而已。
然后说问题：
1、大问题：昨天用2.7版本，红米9，即使选择1s延迟的那个方案，也会突然抢着抢着跑到桌面去（可能返回动作执行多了？），只能不断手动重开美团买菜App进购物车再开抢购。所以这里的延时判断逻辑还有优化空间。

2、次要问题：还是没有成功执行【极速付款】，早上它不知道点了什么会让你无限选择极速付款还是手动付款，没办法把软件卸载了手动选了个配送时间后，疯狂点极速付款。然后成功了。。。。

**Comment by itwangxiang** [comment]
> > > > 你可以尝试将支付订单页面截图我看看，我尝试新增一个方案，然后你试一下
> > > 
> > > 
> > > 可以看这个视频的第41秒，正常其他平台这时候点支付就完了，它从42秒开始，你还要一直点红色的“立即支付”，然后告诉你前面拥堵。（这真的是扯淡，这样做不浪费他们结算服务器并发么，TMD居然提交订单不锁定的，支付还要抢，F*ck） 而盒马就没有这种问题，盒马只要提交了订单，你可以手动慢点付款。
> > > https://www.bilibili.com/video/BV1AY4y1H7Qg?share_source=copy_web
> > 
> > 
> > 理论上我会自动执行的呀，可能间隔太短了，导致模拟点击无法触发了，可以设置大一点
> 
> 看到您辛苦的更新它，我作一定实际情况反馈，它是这样： 先说结果：这这两天美团我都抢到了，您的助手可以抢到订单，只是没有自动支付，后半部分我手动执行极速支付的过程成功了，只是没抢到绿叶菜而已。 然后说问题： 1、大问题：昨天用2.7版本，红米9，即使选择1s延迟的那个方案，也会突然抢着抢着跑到桌面去（可能返回动作执行多了？），只能不断手动重开美团买菜App进购物车再开抢购。所以这里的延时判断逻辑还有优化空间。
> 
> 2、次要问题：还是没有成功执行【极速付款】，早上它不知道点了什么会让你无限选择极速付款还是手动付款，没办法把软件卸载了手动选了个配送时间后，疯狂点极速付款。然后成功了。。。。

问题一，已做优化，直接打开 app ，不错失败的处理方案了
问题二，已新增 - 测试2 - 的方案可以试试

**Comment by jackdiy** [comment]
> > 看到您辛苦的更新它，我作一定实际情况反馈，它是这样： 先说结果：这这两天美团我都抢到了，您的助手可以抢到订单，只是没有自动支付，后半部分我手动执行极速支付的过程成功了，只是没抢到绿叶菜而已。 然后说问题： 1、大问题：昨天用2.7版本，红米9，即使选择1s延迟的那个方案，也会突然抢着抢着跑到桌面去（可能返回动作执行多了？），只能不断手动重开美团买菜App进购物车再开抢购。所以这里的延时判断逻辑还有优化空间。
> > 2、次要问题：还是没有成功执行【极速付款】，早上它不知道点了什么会让你无限选择极速付款还是手动付款，没办法把软件卸载了手动选了个配送时间后，疯狂点极速付款。然后成功了。。。。
> 
> 问题一，已做优化，直接打开 app ，取消失败时，打开买菜助手再打开购物 app 的逻辑 问题二，已新增 - 测试2 - 的方案可以试试

回复一下：
今天早上使用2.8版本使用新增的测试方案，已在红米9上全自动执行到 极速支付成功，感谢您的辛苦付出
