### ISSUE TITLE
支持捡漏吗？

### ISSUE THREAD

**Issue by hema84870000** [universeindream/MaiCaiAssistant#29]
我使用美团紧急模式，打开美团买菜APP，在购物车界面点 浮窗抢购，会提示当前时段约满，然后会自动点掉，来回几次后，就不操作了，需要再次点击浮窗才可以继续尝试，请问怎么改成一直尝试呢？

**Comment by jackdiy** [comment]
按经验美团捡不到什么漏，叮咚和盒马捡漏是有可能的。
叮咚早上手动捡漏了一盒火腿片...
盒马前天手动捡漏了一提得宝的纸

**Comment by hema84870000** [comment]
美团我这边是可以捡漏的，主要是得知道什么时候有运力，后者一直在自动尝试下单才可以。 请问可以设置为一直自动尝试下单的模式吗？  目前看上去好像尝试几次会停止

**Comment by hema84870000** [comment]
在限流抢购的时候，购物车点结算，有一定概率无法弹出“前方拥堵，请稍后再试”这个标签页，而是直接卡住不动，此时过10秒左右，就会自动停止脚本执行，必须再次点击抢购按钮才可以继续，可否改进一下？

**Comment by hema84870000** [comment]
有录下视频，可否留个邮箱？我发送过去

**Comment by itwangxiang** [comment]
当前版本应该没有问题了吧
