### ISSUE TITLE
miui 13没有悬浮窗，开了app悬浮窗后运行程序提示bug报错

### ISSUE THREAD

**Issue by cloveric** [universeindream/MaiCaiAssistant#30]
miui 13没有悬浮窗，开了app悬浮窗后运行程序提示bug报错。

试了好几个版本都一样

**Comment by itwangxiang** [comment]
<img width="885" alt="image" src="https://user-images.githubusercontent.com/7286154/163169755-2171eaba-2cb8-41e9-b7e1-3865052bd204.png">

**Comment by itwangxiang** [comment]
请点击 `ERROR DETAILS` 提供错误记录
