### ISSUE TITLE
无法自动点击支付的问题

### ISSUE THREAD

**Issue by xuanxm** [universeindream/MaiCaiAssistant#33]
美团抢到以后需要手动点击‘结算’按键才能跳到付款的界面，我每次都没有及时手动点击‘结算’所以无法成功，能否加上这个功能？谢谢
![2022-04-14 15 57 19](https://user-images.githubusercontent.com/102497302/163349684-27e1c114-396d-4fd6-a824-a6fb470c261e.JPG)
！

**Comment by itwangxiang** [comment]
可以加微信群，讨论方案
