### ISSUE TITLE
配置里的支付方式没有极速支付和正常支付的切换，导致无法支付。

### ISSUE THREAD

**Issue by ShawnCM** [universeindream/MaiCaiAssistant#37]
https://user-images.githubusercontent.com/103737329/163549245-362377ff-073a-4065-b39a-238b7dc4c839.mp4

**Comment by jackdiy** [comment]
这个和我说的那个是一样的，不过今天早上我及时手动狂点极速支付抢到了。。。

**Comment by itwangxiang** [comment]
试试 - 美团买菜APP抢购 - 极速支付(测试2) - 自动送达时间

**Comment by jackdiy** [comment]
> 试试 - 美团买菜APP抢购 - 极速支付(测试2) - 自动送达时间

又更新了吗？辛苦了，明早试了之后反馈
