### ISSUE TITLE
盒马无法选择时间

### ISSUE THREAD

**Issue by hacker-cat** [universeindream/MaiCaiAssistant#38]
2.1.7的“盒马正常购买“流程，选择时间的时候是直接点击确认，利用系统默认选择了第一个时间。
我想指定一个时间（比如“今日 17:15-17:45送达”），尝试修改方案：用TXT可以找到这个node，判断NODE_CAN_CLICK也是OK的，但是handle里面执行CLICK_NODE却没有效果

**Comment by itwangxiang** [comment]
可以试试图形修改
