### ISSUE TITLE
无法持续循环运行脚本问题

### ISSUE THREAD

**Issue by 578851313** [universeindream/MaiCaiAssistant#44]
测试两台安卓手机，Android11运行一轮就停止，并且触发异常响铃。旧手机Android8测试过程中，可完美循环运行。咨询一下作者如何解决？

**Comment by windherd** [comment]
我是 Android12一样运行一轮就停止.

**Comment by windherd** [comment]
> 测试两台安卓手机，Android11运行一轮就停止，并且触发异常响铃。旧手机Android8测试过程中，可完美循环运行。咨询一下作者如何解决？

GlobalActionBarService第187 行,delay 时间改的大一些.我这边 500 正常.

<img width="527" alt="image" src="https://user-images.githubusercontent.com/15173137/163672222-3e1b474e-270d-408a-a4cc-41b9e2b79971.png">
