### ISSUE TITLE
微信群没法添加？盒马没法操作吗？购物车后无反应？

### ISSUE THREAD

**Issue by FthirtyPro** [universeindream/MaiCaiAssistant#47]
微信群2群没法添加
拉人助手查不此人？被封号了吗？
盒马这个配置好像不成熟
异常提示：步骤：点击购物车-已重复执行了10s 已自动。。。停止了吧。。
不会进入结算界面？还是哪里配置有问题。

**Comment by jackdiy** [comment]
> 微信群2群没法添加 拉人助手查不此人？被封号了吗？ 盒马这个配置好像不成熟 异常提示：步骤：点击购物车-已重复执行了10s 已自动。。。停止了吧。。 不会进入结算界面？还是哪里配置有问题。

作者本人应该很辛苦，他那抢不到任何东西，最好建议你们把手动抢盒马的流程录屏传给作者参考一下。

**Comment by itwangxiang** [comment]
盒马已临时修复

**Comment by lifeishimeizi** [comment]
点击结算后，提交订单界面的提交订单按钮为灰色，异常响铃
