### ISSUE TITLE
助手选择好配送时间后并未点击"极速支付"按钮,并开始弹出铃声.

### ISSUE THREAD

**Issue by dzhen973** [universeindream/MaiCaiAssistant#48]
![1650234095365](https://user-images.githubusercontent.com/43027442/163734406-fd2b38a8-b179-4559-bbbd-dd44067a8fee.jpg)
如图(头次使用助手工具),我选择的是"美团买菜-支付宝"方案,只要到了这个界面就停住了,看起来没有触发任何支付选项,并开始弹铃声.

**Comment by ootvt** [comment]
因为页面上有两个可点击的极速支付按钮，需要点的是第二个

**Comment by dzhen973** [comment]
> 因为页面上有两个可点击的极速支付按钮，需要点的是第二个

所以这还要我手动的去点吗,这和默认配置方案上写的流程不太一样啊.

**Comment by itwangxiang** [comment]
试试 - 美团买菜APP抢购 - 极速支付(测试2) - 自动送达时间

**Comment by ootvt** [comment]
测试2极速支付成功了

**Comment by itwangxiang** [comment]
已处理
