### ISSUE TITLE
无法加载叮咚买菜APP

### ISSUE THREAD

**Issue by simon2000000** [universeindream/MaiCaiAssistant#49]
在买菜助手界面上，选好当前方案 叮咚APP抢购-支付宝-自动送达时间 后，点击悬浮开关抢购，无法启动叮咚买菜APP，2.7和2.8都这样，我用的是GOOGLE PIXEL2XL

**Comment by itwangxiang** [comment]
那暂时手动打开吧，可能是系统不允许唤起应用？

**Comment by itwangxiang** [comment]
已临时修复
