### ISSUE TITLE
美团在捡漏的时候提升“订单已约满”，能不能加一步自己点击“我知道了”

### ISSUE THREAD

**Issue by paranoiagu** [universeindream/MaiCaiAssistant#53]
如题。
捡漏的情况比较有用。

**Comment by itwangxiang** [comment]
这个可以自己尝试下修改，或者群里问问大伙呢

**Comment by jackdiy** [comment]
捡漏的核心问题不在方案上，而在于你的购物车要不断刷新和选择商品，这个逻辑不太好设计的
而且从性价比考量，应该在叮咚和盒马上研究捡漏逻辑优先，因为成功率和品类上都不错。
比如现在全网几乎没有绿叶菜，但叮咚偶尔还能刷出上海青、茼蒿、娃娃菜，盒马还有空心菜等

**Comment by paranoiagu** [comment]
在晚上7、8点钟，美团开始上新，这时候可能会有部分运力释放。这个时候，其实是捡漏的好机会。

**Comment by paranoiagu** [comment]
还有个问题，发现早上6点之前，点击结算，提示6点后才能下单的“我知道了”是可以自己关闭的。
