### ISSUE TITLE
叮咚运行时几次运行后会自动跳到设置界面，然后不动了

### ISSUE THREAD

**Issue by laser-bird** [universeindream/MaiCaiAssistant#57]
不知为什么启动抢购不多一会儿，会自动跳到设置界面，然后不动，2.9.1

**Comment by jackdiy** [comment]
手动抢的话：
先手动编辑配置，把打开App和跳过广告两个步骤删除，然后自己打开叮咚进购物车再点。
但完全全自动就没有了 ，不过我觉得不影响

**Comment by laser-bird** [comment]
> 手动抢的话： 先手动编辑配置，把打开App和跳过广告两个步骤删除，然后自己打开叮咚进购物车再点。 但完全全自动就没有了 ，不过我觉得不影响

好像有效哦，谢谢!

**Comment by itwangxiang** [comment]
v2.9.2
