### ISSUE TITLE
鸿蒙深色模式显示效果不佳

### ISSUE THREAD

**Issue by saberxt** [universeindream/MaiCaiAssistant#63]
![Screenshot_20220423_031839_com.univerindream.maicaiassistant.jpg](https://user-images.githubusercontent.com/103311994/164890124-274c2078-9d48-4091-8075-eaa8e2e99d40.jpg)
中间部分文本对比度太低，夜间根本看不清了

**Comment by itwangxiang** [comment]
v2.10.1
