### ISSUE TITLE
打开软件条件设置为“软件后台”，保存无效

### ISSUE THREAD

**Issue by commis** [universeindream/MaiCaiAssistant#72]
version：3.0
打开软件时，设置条件为判断”软件后台“，保存后条件为”控件存在“。

对于内置的”美团买菜“修改打开软件的条件，将“软件后台”改为其他条件保存后，再次修改回“软件后台”，再保存无效，依旧是“控件存在”。

**Comment by kimliss** [comment]
已修复，确实是个 bug
